name: Ordering System
run-name: ${{github.event.head.commit.messages}}
on: 
  push:
    tags:
        - v*
jobs:
  ordering-system:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.upload-program.outputs.artifact-id}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Setup GO version
        uses: actions/setup-go@v6
        with:
          go-version: '1.26'
      - name: Installing GO dependencies
        run: go mod tidy
      - name: build app
        run: go build -o ordering-system main.go
      - name: Save artifact
        uses: actions/upload-artifact@v7
        id: upload-program
        with:
          name: build-result
          path: ./ordering-system
  release-app:
    name: "Release builded app"
    needs: ordering-system
    runs-on: ubuntu-latest
    steps:
        - name: Download artifact
          uses: actions/download-artifact@v8
          with:
            artifact-ids: ${{needs.ordering-system.outputs.output1}}
        - name: Compress artifact
          run: zip -r ordering-system.zip .
        - name: Release
          uses: softprops/action-gh-release@v3
          with:
            files: ordering-system.zip
            overwrite_files: true
            token: ${{secrets.GITHUB_TOKEN}}
            tag_name: ${{github.ref_name}}
  on-succes:
    name: "Build image"
    needs: ordering-system
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v7
        - name: Login to docker
          run: echo -n ${{secrets.GITHUB_TOKEN}}| docker login ghcr.io --username ${{github.actor}} --password-stdin
        - name: Download artifact
          uses: actions/download-artifact@v8
          with:
            artifact-ids: ${{needs.ordering-system.outputs.output1}}
        - name: Build images
          run: docker build . -t ghcr.io/${{github.repository}}:latest
        - name: Push to ghcr.io
          run: docker push ghcr.io/${{github.repository}}:latest
            